# Name of the pipeline
name: ETL Pipeline Demo

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

# Define jobs
jobs:
  extract-data-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v6
        with:
            python-version: '3.10'
    
      - name: show python version
        run: python --version

      - name: Run extract.py
        run: python extract.py

  transform-data-job:
    runs-on: ubuntu-latest
    needs: extract-data-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run transform.py
        run: python transform.py

  load-data-job:
    runs-on: ubuntu-latest
    needs: transform-data-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run load.py
        run: python load.py
